# Generated by Django 4.1.3 on 2023-02-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='payment_request_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='createdDate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='modified_at',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='purpose',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='webhook_url',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
