# Generated by Django 4.1.3 on 2023-02-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_order_id_order_payment_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='productName',
            field=models.CharField(max_length=500),
        ),
    ]
